# DATAFRAME

In [1]:
print("I love you")

I love you

In [2]:
import pandas as pd

data = {
    'Name': ['Aariyan', 'Rashmi', 'Krishna'],
    'Age' : [24, 22, 1800],
    'Gender': ['Male', 'Female', 'Male']
}

df = pd.DataFrame(data)
print(df)

      Name   Age  Gender
0  Aariyan    24    Male
1   Rashmi    22  Female
2  Krishna  1800    Male

## Creating Dataframes from list

In [3]:
data = [
    ['Aariyan', 24, 'SE'],
    ['Rashmi', 22, 'BA'],
    ['Krishna', 1800, 'Annoying Rashmi']
]

df1 = pd.DataFrame(data, columns= ['Name', 'Age', 'Profession'])
print(df1)

      Name   Age       Profession
0  Aariyan    24               SE
1   Rashmi    22               BA
2  Krishna  1800  Annoying Rashmi

## Reading CSV file

In [4]:
read = pd.read_csv(r"D:\Documents\Calcutta Business School\3rd Trimester\FBA\Data Structure.xlsx")

UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd1 in position 16: invalid continuation byte

In [ ]:
read.head()

NameError: name 'read' is not defined

In [5]:
import pandas as pd
df = pd.read_csv(r"C:\Users\Win11\Downloads\Social Media Toothless - LinkedIn CC.csv")

In [6]:
df.head()

,Day,Theme,Hook (First Line),Content Summary,CTA,Tag Suggestions,Format,Link,Date Posted
0,1,Introduction,"""From college labs to enterprise codebases—thi...",Intro post: From B.Tech to Software Engineer a...,"""Drop a 🔥 if you're a fresh grad stepping into...",@SaskenTech @LinkedInIndia,Text,Link,07-Jul-25
1,2,Tech Insight,"""The #1 thing I learned in my first month as a...",Share a lesson that surprised you post-joining,"""What shocked you most when you entered the in...",@GitHub @FreeCodeCamp,Text,Link,08-Jul-25
2,3,Personal Story,"""I failed this interview—and it made me 10x be...",Vulnerable post about a rejection that shaped you,"""Tag someone who needs to hear this today.""",@ScalerOfficial @TechCrunch,Story Post,Link,09-Jul-25
3,4,Tech Trend,"""AI won’t replace devs—but devs using AI will ...",Talk about using AI tools like Copilot or ChatGPT,"""Which AI tool is in your stack? Comment below.""",@OpenAI @GitHubCopilot,Carousel,Link,10-Jul-25
4,5,Poll,"""Which is hardest for fresh grads in Software ...","Poll: Communication, DSA, Development, Finding...","""Vote + comment why!""",@CodeChef @LinkedInNews,Poll,Link,11-Jul-25

In [7]:
df.tail()

,Day,Theme,Hook (First Line),Content Summary,CTA,Tag Suggestions,Format,Link,Date Posted
25,26,Behind-the-Scenes,"""How I plan my week for deep focus + content""",Share routine and tips,"""Want a template? Comment ‘Plan’""",@AliAbdaal @Notion,Text + Image,Link,28-Jul-25
26,27,Hook Story,"""In 2 minutes, I gained the trust of the entir...","Short, sharp story about interview or pitch","""What’s the best thing you ever said in an int...",@InterviewReady,Story Format,Link,29-Jul-25
27,28,Milestone,"""We crossed 5K! This is wild.""",Community-focused gratitude post,"""Comment your goal. Let’s win together.""",Tag top commenters from prior posts,Text + Image,Link,NaN
28,29,Collab Invite,"""Let’s co-write a carousel on modern tech ritu...",Collaboration CTA,"""Comment 🔗 and I’ll DM.""","Tag micro-creators in dev, product",Text,Link,NaN
29,30,Recap,"""30 days, 10K+ new connections, 100 lessons.""","Reflect on the challenge, share insights","""Want a guide of everything I learned? Comment...",Tag mentors and standout commenters,Long-Form Post,Link,NaN

In [8]:
df.head(6)

,Day,Theme,Hook (First Line),Content Summary,CTA,Tag Suggestions,Format,Link,Date Posted
0,1,Introduction,"""From college labs to enterprise codebases—thi...",Intro post: From B.Tech to Software Engineer a...,"""Drop a 🔥 if you're a fresh grad stepping into...",@SaskenTech @LinkedInIndia,Text,Link,07-Jul-25
1,2,Tech Insight,"""The #1 thing I learned in my first month as a...",Share a lesson that surprised you post-joining,"""What shocked you most when you entered the in...",@GitHub @FreeCodeCamp,Text,Link,08-Jul-25
2,3,Personal Story,"""I failed this interview—and it made me 10x be...",Vulnerable post about a rejection that shaped you,"""Tag someone who needs to hear this today.""",@ScalerOfficial @TechCrunch,Story Post,Link,09-Jul-25
3,4,Tech Trend,"""AI won’t replace devs—but devs using AI will ...",Talk about using AI tools like Copilot or ChatGPT,"""Which AI tool is in your stack? Comment below.""",@OpenAI @GitHubCopilot,Carousel,Link,10-Jul-25
4,5,Poll,"""Which is hardest for fresh grads in Software ...","Poll: Communication, DSA, Development, Finding...","""Vote + comment why!""",@CodeChef @LinkedInNews,Poll,Link,11-Jul-25
5,6,Biz + Tech,"""Most startups fail not due to tech—but lack o...",Startup insight for non-tech audience,"""Agree or disagree? Let’s debate.""",@a16z @SaaStr @HarvardBiz,Text,Link,12-Jul-25

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 9 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Day                30 non-null     int64
 1   Theme              30 non-null     object
 2   Hook (First Line)  30 non-null     object
 3   Content Summary    30 non-null     object
 4   CTA                30 non-null     object
 5   Tag Suggestions    30 non-null     object
 6   Format             30 non-null     object
 7   Link               30 non-null     object
 8   Date Posted        22 non-null     object
dtypes: int64(1), object(8)
memory usage: 2.2+ KB

In [10]:
df.describe()

             Day
count  30.000000
mean   15.500000
std     8.803408
min     1.000000
25%     8.250000
50%    15.500000
75%    22.750000
max    30.000000

In [12]:
df.columns

Index(['Day', 'Theme', 'Hook (First Line)', 'Content Summary', 'CTA',
       'Tag Suggestions', 'Format', 'Link', 'Date Posted'],
      dtype='object')

In [13]:
df.head(2)

,Day,Theme,Hook (First Line),Content Summary,CTA,Tag Suggestions,Format,Link,Date Posted
0,1,Introduction,"""From college labs to enterprise codebases—thi...",Intro post: From B.Tech to Software Engineer a...,"""Drop a 🔥 if you're a fresh grad stepping into...",@SaskenTech @LinkedInIndia,Text,Link,07-Jul-25
1,2,Tech Insight,"""The #1 thing I learned in my first month as a...",Share a lesson that surprised you post-joining,"""What shocked you most when you entered the in...",@GitHub @FreeCodeCamp,Text,Link,08-Jul-25

In [16]:
df["Theme"][0] = "Intro"

C:\Users\Win11\AppData\Local\Temp\ipykernel_18924\1779175508.py:1: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df["Theme"][0] = "Intro"
C:\Users\Win11\AppData\Local\Temp\ipykernel_18924\1779175508.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Theme"][0] = "Intro"

In [17]:
df.head(2)

,Day,Theme,Hook (First Line),Content Summary,CTA,Tag Suggestions,Format,Link,Date Posted
0,1,Intro,"""From college labs to enterprise codebases—thi...",Intro post: From B.Tech to Software Engineer a...,"""Drop a 🔥 if you're a fresh grad stepping into...",@SaskenTech @LinkedInIndia,Text,Link,07-Jul-25
1,2,Tech Insight,"""The #1 thing I learned in my first month as a...",Share a lesson that surprised you post-joining,"""What shocked you most when you entered the in...",@GitHub @FreeCodeCamp,Text,Link,08-Jul-25

In [18]:
df.to_csv("Moto.csv", index= False)